name: Translate README

on:
  push:
    paths:
      - 'README.md'
      
permissions:
  contents: write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Translate README
        uses: humonnom/readme-in-japanese@v1
        with:
          api_key: ${{ secrets.OPENAI_API_KEY }}
