name: Translate README

on:
  push:
    paths:
      - 'README.md'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Translate README
        uses: humonnom/translateme@v1
        with:
          api_key: ${{ secrets.OPENAI_API_KEY }}
